id = "mcp-server-webflow"
name = "Webflow MCP Server"
description = "Model Context Protocol Server for Webflow"
version = "0.0.1"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
repository = "https://github.com/LoamStudios/zed-mcp-server-webflow"

[context_servers.mcp-server-webflow]
name = "Webflow MCP Server"
